//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivePassword
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UsedPassword { get; set; }
    
        public virtual UserLogIn UserLogIn { get; set; }
    }
}
