//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleRented
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ArticleId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime Rented { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
